version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: marketing_hub_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketing_hub_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d marketing_hub_dev"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Опциональный pgAdmin для удобства управления БД
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: marketing_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
